apiVersion: v1
kind: ServiceAccount
metadata:
  name: qualitygate-sa
  namespace: cerberus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qualitygate-role
  namespace: cerberus
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qualitygate-rolebinding
  namespace: cerberus
subjects:
  - kind: ServiceAccount
    name: qualitygate-sa
    namespace: cerberus
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: qualitygate-role