apiVersion: v1
kind: Secret
metadata:
  name: azure-postgres-secret
  namespace: cerberus
type: Opaque
stringData:
  DB_HOST: "34.198.134.147"
  DB_PORT: "5432"
  DB_NAME: "cerberus"
  DB_USER: "cerberus"
  DB_PASSWORD: "cerberus123"