name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  validate-cluster:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Validate Kubernetes Cluster
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e

            echo "Servidor:"
            hostname

            echo ""
            echo "Version kubectl:"
            kubectl version --client

            echo ""
            echo "Nodos:"
            kubectl get nodes

            echo ""
            echo "Namespaces:"
            kubectl get ns
          EOF